<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');   
$storeName     = $storeManager->getStore()->getName();
if ($customerSession->isLoggedIn()) {
    $groupRepository  = $objectManager->create('\Magento\Customer\Api\GroupRepositoryInterface');
    $group = $groupRepository->getById($customerSession->getCustomer()->getGroupId());?>
    <div class="control">
    <input type="radio" checked name="group_id" value="<?php echo $customerSession->getCustomer()->getGroupId() ?>">  
    <span class='lable-radio'><?php 
    if($customerSession->getCustomer()->getGroupId() == '5' && strtolower($storeName) == "italiano"){
        echo "Cliente";
    } 
    elseif($customerSession->getCustomer()->getGroupId() == '3' && strtolower($storeName) == "italiano"){
        echo "Gioielleria";
    }
    else{
     
        echo $group->getCode();
    }
    ?></span>
    </div>
<?php } ?>

<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
      
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <div style="display: none;" class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?php $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox"/>
            <label class="label" for="change-email"><span><?php echo $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php echo $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"/>
            <label class="label" for="change-password"><span><?php echo $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>

    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">

        <legend class="legend"><span data-title="change-email-password"><?php $block->escapeHtml(__('Change Email and Password')) ?></span></legend><br>

        <div class="field email required" data-container="change-email">

            <label class="label" for="email"><span><?php $block->escapeHtml(__('Email')) ?></span></label>

            <div class="control">
                <input type="email" name="email" placeholder="Email" id="email" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
<!--
            <label class="label" for="current-password"><span><?php //$block->escapeHtml(__('Current Password')) ?></span></label>
-->
            <div class="control">
                <input type="password" class="input-text" placeholder="<?php echo __('Current Password*') ?>" name="current_password" id="current-password" title="<?= $block->escapeHtmlAttr(__('Current Password*')) ?>" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
<!--
            <label class="label" for="password"><span><?php //$block->escapeHtml(__('New Password')) ?></span></label>
-->
            <div class="control">
                <input type="password" class="input-text" name="password" title="<?= $block->escapeHtmlAttr(__('New Password')) ?>" placeholder="<?php echo __('New Password') ?>" id="password"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
<!--
            <label class="label" for="password-confirmation"><span><?php //$block->escapeHtml(__('Confirm New Password')) ?></span></label>
-->
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm New Password')) ?>" placeholder="<?php echo __('Confirm New Password') ?>" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
    </fieldset>
    <?php //$block->getChildHtml('form_additional_info') ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>

<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>

<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
