<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
        
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Login')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?php //$block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you are already registered, please login.')) ?></div>
                <div class="field email required">
<!--
                    <label class="label" for="email"><span><?php //$block->escapeHtml(__('Email')) ?></span></label>
-->
                    <div class="control login">
                        <input name="login[username]" placeholder="<?php echo __('Username*') ?>" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
<!--
                    <label for="pass" class="label"><span><?php //$block->escapeHtml(__('Password')) ?></span></label>
-->
                    <div class="control pass">
                        <input name="login[password]" placeholder="<?php echo __('Password*') ?>" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar forgot-pass">
					<div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
                    <div class="primary signin"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('LOGIN')) ?></span></button></div>
<!--
                    <div class="primary create-acc">
                <a href="<?php //$block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?php //$block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
-->
                   <div class="or"><span><?php echo __("Or") ?></span></div> 
            </fieldset>
        </form>
    </div>
</div>

