<form id="example-advanced-form" method="post" action="<?= $block->getUrl('certificato/index/certi'); ?>">
	 <legend>Account Information</legend>
    <h3>Dati anagrafici</h3>
    <fieldset>
       
        
 
        <label for="name-2">Name *</label>
        <input id="name-2" name="name" placeholder="Name*" type="text" >
        <label for="surname-2">Surname *</label>
        <input id="surname-2" name="surname" placeholder="Surname*" type="text" >
		<label for="address-2">Address</label>
        <input id="address-2" name="address" placeholder="Address*" type="text" >
		<label for="zipcode-2">Zipcode</label>
        <input id="zipcode-2" name="zipcode" placeholder="Zipcode*" type="text" >
		<label for="city-2">City</label>
        <input id="city-2" name="city" placeholder="City*" type="text">
		<label for="province-2">Province </label>
        <input id="province-2" name="province " placeholder="Province*" type="text">
		<label for="state-2">State</label>
        <input id="state-2" name="state" placeholder="State*" type="text">
		<label for="phone -2">Telephone</label>
        <input id="phone -2" name="phone " placeholder="Telephone*" type="text">
		<label for="mobile_phone-2">Mobile Phone</label>
        <input id="mobile_phone-2" name="mobile_phone" placeholder="Mobile Phone*" type="text">
		<label for="fiscal_code-2">Fiscal Code</label>
        <input id="fiscal_code-2" name="fiscal_code" placeholder="Fiscal Code*" type="text">
		<label for="dob-2">Date Of Birth</label>
        <!--input id="dob-2" name="dob" placeholder="Date Of Birth*" type="text"-->
		 <input type="text"  placeholder="Date Of Birth*"
           id="calendar_inputField" 
           name="dob"
          />
		<label for="sex-2">Sex</label>
        <input id="sex-2" name="sex" placeholder="Sex*" type="text">
		<label for="email-2">Email *</label>
        <input id="email-2" name="email" placeholder="Email*" type="text" >
<!--
        <p>(*) Mandatory</p>
-->
    </fieldset>
 
    <h3>Info generiche</h3>
    <fieldset>
        <legend>Profile Information</legend>
		<select name="civil_status">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="degree_education">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="profession">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="civil_status">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="buying_opportunity">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="reason_purchase">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="reason_choice">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		<select name="came_to_know">
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>
		</select>
		
<!--
        <p>(*) Mandatory</p>
-->
    </fieldset>
 
    <h3>Dati prodotto e acquisto</h3>
    <fieldset>
        <label for="equpiment-2">Equpiment *</label>
        <input id="equpiment-2" name="equpiment" placeholder="Equpiment*" type="text" >
        <label for="model-2">Model *</label>
        <input id="model-2" name="model" placeholder="Model*" type="text" >
		<label for="serial_number-2">Serial Number </label>
        <input id="serial_number-2" name="serial_number" placeholder="Serial Number*" type="text" >
		<label for="name_boutique_retailer-2">Name Boutique / Retailer </label>
        <input id="name_boutique_retailer-2" name="name_boutique_retailer" placeholder="Name Boutique / Retailer*" type="text" >
		<label for="add_boutique_retailer-2">Add Boutique / Retailer </label>
        <input id="add_boutique_retailer-2" name="add_boutique_retailer" placeholder="Add Boutique / Retailer*" type="text">
        <label for="add_boutique_retailer-2">Nome del venditore </label>
        <input id="add_boutique_retailer-2" name="add_boutique_retailer" placeholder="Nome del venditore*" type="text">
        <label for="add_boutique_retailer-2">Data acquisto </label>
        <input id="add_boutique_retailer-2" name="add_boutique_retailer" placeholder="Data acquisto*" type="text">
        <label for="add_boutique_retailer-2">Immagine scontrino (Jpg, Png, Pdf) </label>
    </fieldset>
 
    <h3>Firma documento	</h3>
    <fieldset>
        <legend>Terms and Conditions</legend>
 
        <input id="acceptTerms-2" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms-2">I agree with the Terms and Conditions.</label>
		
		<button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
    </fieldset>
</form>
<script type="text/javascript">

        require([
            "jquery",
            "mage/calendar"
        ], function ($) {
            $("#calendar_inputField").calendar({
                changeYear: true,
                changeMonth: true,
                yearRange: "1970:2050",
                buttonText: "Select Date",
            });
        });
 
    require([ 'jquery', 'steps'], function($){ 
	
   var form = $("#example-advanced-form").show();
	form.steps({
    headerTag: "h3",
    bodyTag: "fieldset",
    transitionEffect: "slideLeft",
    onStepChanging: function (event, currentIndex, newIndex)
    {
        // Allways allow previous action even if the current form is not valid!
        if (currentIndex > newIndex)
        {
            return true;
        }
        // Forbid next action on "Warning" step if the user is to young
        if (newIndex === 3 && Number($("#age-2").val()) < 18)
        {
            return false;
        }
        // Needed in some cases if the user went back (clean up)
        if (currentIndex < newIndex)
        {
            // To remove error styles
            form.find(".body:eq(" + newIndex + ") label.error").remove();
            form.find(".body:eq(" + newIndex + ") .error").removeClass("error");
        }
        form.validate().settings.ignore = ":disabled,:hidden";
        return form.valid();
    },
    onStepChanged: function (event, currentIndex, priorIndex)
    {
        // Used to skip the "Warning" step if the user is old enough.
        if (currentIndex === 2 && Number($("#age-2").val()) >= 18)
        {
            form.steps("next");
        }
        // Used to skip the "Warning" step if the user is old enough and wants to the previous step.
        if (currentIndex === 2 && priorIndex === 3)
        {
            form.steps("previous");
        }
    },
    onFinishing: function (event, currentIndex)
    {
        form.validate().settings.ignore = ":disabled";
        return form.valid();
    },
    onFinished: function (event, currentIndex)
    {
        alert("Submitted!");
    }
}).validate({
    errorPlacement: function errorPlacement(error, element) { element.before(error); },
    rules: {
        confirm: {
            equalTo: "#password-2"
        }
    }

}); });</script>
