<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeName     = $storeManager->getStore()->getName();
$storeId = $block->getKey();
$base_url_config = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue("web/unsecure/base_url");


if($storeId == '1'){
  $st = "it";
}else{
  $st = "en";
}
$action = $base_url_config.$st."/customer/account/createpost/";
?>
<div class="client-create-account">
<form class="form create account form-create-account" action="<?= $action ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
	<fieldset class="fieldset create info">
       <br>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <!-- <input type="hidden" name="lastname" value="testnew"> -->



    </fieldset>
	<?php $block->setShowAddressFields(true); ?>
    <?php if ($block->getShowAddressFields()): ?>

        <fieldset class="fieldset address">

            <input type="hidden" name="create_address" value="1" />

            <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
            <?php if ($_company->isEnabled()): ?>
                <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
            <?php endif ?>

			<div class="field required">

            <div class="control">
                <input type="text" name="vat-number" id="vat-number-2" value="" title="<?php echo __('VAT number*') ?>" placeholder="<?php echo __('VAT number*') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>

<div class="field country required">
                <div class="control">
                    <?= $block->getCountryHtmlSelect($defValue = 'IT') ?>
                </div>
            </div>

			<div class="field required">

                <div class="control">
                    <input type="text" name="city" placeholder="<?php echo __('City*') ?>" title="<?php echo __('City*') ?>" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>"  class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>" id="city">
                </div>
            </div>



            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">

                <div class="control">
                    <input type="text" name="street[]" placeholder="<?php echo __('Address*') ?>" title="<?php echo __('Address*') ?>"  value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>"  id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">

                </div>
            </div>




            <div class="field zip required">

                <div class="control">
                    <input type="text" name="postcode" title="<?php echo __('Postal Code*') ?>" placeholder="<?php echo __('Postal Code*') ?>" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>"  id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                </div>
            </div>
            <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
            <?php endif ?>


            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
    <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

        <div class="field required">

            <div class="control">
                <input type="email" name="email" placeholder="<?php echo __('Email*') ?>" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email*')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field password required">

            <div class="control">
                <input type="password" name="password" placeholder="Password*" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password*')) ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">

            </div>

        </div>

     <?php if(strtolower($storeId) == '1'){?>
     <div class="client-contain"><p><?php echo __("Registrando i tuoi dati, accetti i nostri ".'<a target="_blank" href="https://www.damianigroup.com/termini-e-condizioni/" >'."terms and conditions ,".'</a>'.'<a target="_blank" href="https://www.damianigroup.com/privacy/">'."Politica sulla privacy e sui cookie".'</a>'); ?></p></div>
        <?php }else{ ?>

 <div class="client-contain"><p><?php echo __("By registering your data, you agree to our ".'<a target="_blank" href="https://www.damianigroup.com/termini-e-condizioni/" >'."terms and conditions".'</a>'.",".'<a target="_blank" href="https://www.damianigroup.com/privacy/">'."Privacy and Cookie Policy".'</a>'); ?></p></div>

    <?php } ?>
        <?= $block->getChildHtml('form_additional_info') ?>

		<!-- <?php//if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ //echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" checked="checked" class="checkbox">
                <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ //echo __('Sign Up for Newsletter') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php //echo $block->getChildHtml('customer.form.register.newsletter')?>
        <?php// endif ?> -->

    </fieldset>
	<input type="hidden" name="group_id" value="3" />
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
</div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = 'null' ;

    dataForm.mage('validation', {
  /*
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'*/

    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
