<?php 
	$websiteCode = $block->getWebsiteStoreCode();
	$baseUrl = $block->getWebBaseUrl();
?>
<div class="footer-drops-list">
	<?php if($websiteCode == "it"){ ?>
	<div class="footer-item">
		<label>CAMBIO PAESE:</label>		
			<a href="javascript:;" class="storeswitcherlang storeswitchercountry_bottom">Italiano</a> <span class="sparator">/</span> 
			<a href="javascript:;" class="storeswitchercountry_bottom">Italia</a>
			<ul class="countrylistbottom" style="display: none;">
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Austria</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Belgio</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Bulgaria</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Cipro</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Croazia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Danimarca</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Estonia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Finlandia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Francia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Germania</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Grecia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Irlanda</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lettonia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lituania</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lussemburgo</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Malta</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Paesi Bassi</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Polonia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Portogallo</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Regno Unito</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Repubblica Ceca</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Romania</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Slovacchia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Slovenia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Spagna</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Svezia</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Ungheria</a></li>
				<li><a class="underline-hover" href="<?php echo $baseUrl ?>ch">Switzerland</a></li>
			</ul>		
	</div>
	<!-- <div class="footer-item">
		<label>CAMBIO LINGUA:</label>
		<select >
			<option value="">Italiano</option>
		</select>
	</div> -->
	<?php } else if($websiteCode == "ch") { ?>	
	<div class="footer-item">
		<label>CAMBIO PAESE:</label>		
		<a href="javascript:;" class="storeswitcherlang storeswitchercountry_bottom">English</a> <span class="sparator">/</span> 
		<a href="javascript:;" class="storeswitchercountry_bottom">Switzerland</a>
		<ul class="countrylistbottom" style="display: none;">
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>it">Italia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Austria</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Belgio</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Bulgaria</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Cipro</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Croazia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Danimarca</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Estonia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Finlandia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Francia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Germania</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Grecia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Irlanda</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lettonia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lituania</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lussemburgo</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Malta</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Paesi Bassi</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Polonia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Portogallo</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Regno Unito</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Repubblica Ceca</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Romania</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Slovacchia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Slovenia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Spagna</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Svezia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Ungheria</a></li>			
		</ul>
	</div>	
	<!-- <div class="footer-item">
		<label>CAMBIO LINGUA:</label>
		<select >
			<option value="">English</option>
		</select>
	</div> -->
	<?php } else { ?>
	<div class="footer-item">
		<label>CAMBIO PAESE:</label>		
		<a href="javascript:;" class="storeswitcherlang storeswitchercountry_bottom">Europe</a> <span class="sparator">/</span> 
		<a href="javascript:;" class="storeswitchercountry_bottom">English</a>			
		<ul class="countrylistbottom" style="display: none;">
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>it">Italia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Austria</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Belgio</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Bulgaria</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Cipro</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Croazia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Danimarca</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Estonia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Finlandia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Francia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Germania</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Grecia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Irlanda</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lettonia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lituania</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Lussemburgo</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Malta</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Paesi Bassi</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Polonia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Portogallo</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Regno Unito</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Repubblica Ceca</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Romania</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Slovacchia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Slovenia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Spagna</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Svezia</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>eu">Ungheria</a></li>
			<li><a class="underline-hover" href="<?php echo $baseUrl ?>ch">Switzerland</a></li>			
		</ul>
	</div>
	<!-- <div class="footer-item">
		<label>CAMBIO LINGUA:</label>
		<select >
			<option value="">English</option>
		</select>
	</div>	 -->			
	<?php } ?>
</div>

<script>
require(['jquery', 'jquery/ui'], function($){
	$(document).on("click",function(e){
		if(e.target == document.querySelector('.storeswitchercountry_bottom')){			
			if($(".countrylistbottom").hasClass('open')){
				$(".countrylistbottom").removeClass('open');
				$(".countrylistbottom").hide("slow");
			} else {
				$(".countrylistbottom").addClass('open');
				$(".countrylistbottom").show("slow");
			}	
		} else {
			$(".countrylistbottom").removeClass('open');
			$(".countrylistbottom").hide("slow");
		}
	});
});
</script>