<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Pwa
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<meta name="theme-color" content="<?= $block->escapeHtml($block->getThemeColor()); ?>">
<link href="<?= $block->escapeUrl($block->getSecureUrl()); ?>manifest.json" rel="manifest" crossorigin="use-credentials" />
