<?php $isEnable = $block->getConfig('faqtab/general/enable') ?>
<?php $showGroup = $block->getConfig('faqtab/general/showgroup') ?>
<?php $showGroupTitle = $block->getConfig('faqtab/general/showgrouptitle') ?>
<?php $pageType = $block->getConfig('faqtab/general/page_type') ?>
<?php $faqGroupCollection = $block->getFaqGroupCollection() ?>
<?php if ($faqGroupCollection->getSize()) : ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$base_url_config = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue("web/unsecure/base_url");?>
    <?php if ($isEnable) : ?>
<div class="loading-mask" id="cload" data-role="loader">
    <div class="loader">
        <img alt="Loading..." src="<?php echo $this->getViewFileUrl('images/loader-2.gif'); ?>">
        <p>Please wait...</p>
    </div>
</div>
    <div class="faq-collection" id="faq-collection" style="display: none;">
        <?php if ($showGroup) : ?>
            <div class="faq-groups">
                <?php foreach ($faqGroupCollection as $group) : ?>
                    <div class="faq-group">
                        <div id="faq-group-image" class="faq-group-image">
                            <a href="#group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>" class="group-link" groupId="<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                            <?php if ($group->getIcon()) : ?>
                                <img class="group-image"
                                     src="<?php /* @noEscape */ echo $block->getImageUrl($group->getIcon()); ?>" />
                            <?php else : ?>
                                <img class="group-image" 
                                     src="<?php /* @noEscape */ echo $block->getViewFileUrl('Prince_Faq::images/faq.png'); ?>" />
                            <?php endif; ?>
                            </a>
                        </div>
                        <?php if ($showGroupTitle) : ?>
                            <div class="faq-groupname">
                                <a href="#group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>" class="group-link" groupId="<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                                    <?php /* @noEscape */ echo $group->getGroupName(); ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <div id="faq-content" class="faq-content">
            <?php if ($pageType == 'scroll') : ?>
                <?php foreach ($faqGroupCollection as $group) : ?>
                    <?php if ($showGroupTitle) : ?>
                        <div class="group-title" id="group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                            <i></i><?php /* @noEscape */ echo $group->getGroupName(); ?>
                        </div>
                    <?php endif; ?>
                    <div class="faq-accordion">
                    <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
                        <?php if ($faqCollection->getSize()) : ?>
                            <?php foreach ($faqCollection as $faq) : ?>
                                <h3><?php /* @noEscape */ echo $faq->getTitle(); ?></h3>
                                <div>
                                    <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq->getContent()); ?></p>
                                </div>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <div><?php /* @noEscape */ echo __('No FAQ available'); ?></div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            <?php else :?>
                <?php $group = $faqGroupCollection->getFirstItem(); ?>
                <?php if ($showGroupTitle) : ?>
                    <div class="group-title" id="group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                        <i></i><?php /* @noEscape */ echo $group->getGroupName(); ?>
                    </div>
                <?php endif; ?>
                <div class="faq-accordion">
                    <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
                    <?php if ($faqCollection->getSize()) : ?>
                        <?php foreach ($faqCollection as $faq) : ?>
						<?php
						if(isset($_REQUEST['fb']) && $_REQUEST['fb']!= ''){							
							if($faq->getData('faq_id') <= 18){
								continue;
							}
						}else{
							if($faq->getData('faq_id') >= 19){
								continue;
							}
						}
						?>
						
                            <h3><?php /* @noEscape */ echo $faq->getTitle(); ?></h3>
                            <div>
                                <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq->getContent()); ?></p>
                            </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <div><?php /* @noEscape */ echo __('No FAQ available'); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
<?php else : ?>
    <div>
        <h1><?php /* @noEscape */ echo __('No FAQ Group available'); ?></h1>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "faq": {
                "pageType" : "<?php echo $pageType ?>",
                "ajax_url" : "<?php echo $this->getUrl() ?>"
            }
        }
    }
</script>

<script type="text/javascript">
    require(['jquery','jquery/ui',],
            function ($) {
            'use strict';
    $(document).ready(function() {
        var state = document.readyState
        if (state == 'interactive') {
            document.getElementById('faq-collection').style.visibility = "hidden";
        }
    });
    $(document).ready(function() {
        //console.log("div hide");
        
            setTimeout(function () {
                document.getElementById('interactive');
                document.getElementById('cload').style.visibility = "hidden";
                document.getElementById('faq-collection').style.visibility = "visible";
                $('#faq-collection').show();
            }, 3000);
    });
    });
    </script>